# SPDX-License-Identifier: GPL-2.0
#dtb-$(CONFIG_SOC_EXYNOS9610) += \
#	exynos9610-universal9610.dtbo \
#	exynos9611-universal9611.dtbo

dtbo-$(CONFIG_SOC_EXYNOS9610) += \
	exynos9611-m21_swa_open_00.dtbo \
	exynos9611-m21_swa_open_06.dtbo

always		:= $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtbo
